# Redirect with a 301
[[redirects]]
from = "/blog"
to = "/posts"
status = 301
force = true

[[redirects]]
from = "/blog/tags/*"
to = "/tags/:splat"
status = 301
force = true

[[redirects]]
from = "/blog/*"
to = "/posts/:splat"
status = 301
force = true