[build]
publish = "dist"
command = "npx pnpm run build"

[[redirects]]
from = "/blog/tags/*"
to = "/tags/:splat"
status = 301
force = true

[[redirects]]
from = "/blog/*"
to = "/posts/:splat"
status = 301
force = true

[[redirects]]
from = "/blog"
to = "/posts"
status = 301
force = true
